name: 'nyc_analytics'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"] 

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
 nyc_analytics:
   +materialized: table

   assignment_work:
     staging:
       +materialized: table
       +schema: nyc_transit_restaurants_staging

     marts:
       +materialized: table
       +schema: nyc_transit_restaurants_marts
      
       shared:
         +materialized: table

       open_restaurant_apps:
         +materialized: table
         +schema: nyc_open_restaurant_apps

       dot_311:
         +materialized: table
         +schema: nyc_311_dot

# Copied exactly the same structure as above
   cis9440_group_project_work:
     staging:
       +materialized: table
       +schema: WHATEVER YOU ALL DECIDE YOUR STAHING DATASET NAME SHOULD BE TOGETHER

     marts:
       +materialized: table
       +schema: wHATEVER YOU ALL DECIDE YOUR WAREHOUSE DATASET NAME SHOULD BE 
      
       conformed:
         +materialized: table

       data_source_not_311_whatever_that_is:
         +materialized: table
         +schema: nyc_open_restaurant_apps

       Whatever_your_311_subset_data_is:
         +materialized: table
         +schema: nyc_311_dot         